version: '3.9'

services:
  db:
    image: postgres:17
    container_name: product-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: product-api

    depends_on:
      - db

    environment:
      APP_ENV: docker

    env_file:
      - .env.docker

    ports:
      - '8000:8000'

volumes:
  postgres_data:
